version: '3'

services:
 db:
  build: ./mariadb
  container_name: mariadb_inception
  networks:
   - net-db
  volumes:
   - /home/tvanbesi/data/database:/var/lib/mysql
  restart: always

 wordpress:
  build: ./wordpress
  container_name: wordpress_inception
  networks:
   - net-db
   - net-php
  volumes:
   - /home/tvanbesi/data/wordpress:/var/www/html
  depends_on:
   - db
  restart: always

 nginx:
  build: ./nginx
  container_name: nginx_inception
  networks:
   - net-php
  volumes:
   - /home/tvanbesi/data/wordpress:/var/www/html
  ports:
   - 8080:80
  depends_on:
   - wordpress
  restart: always

networks:
 net-db:
 net-php:
